version: '3.6'

services:
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/smart-brain-api
    env_file:
      - ./.env
    ports:
     - "3010:3010"    
    volumes:
      - ./:/usr/src/smart-brain-api
  
  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes: 
  database-data: