version: "3"
services:
  database:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    env_file: 
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d

volumes: 
  database-data: