BEGIN TRANSACTION;

CREATE TABLE users (
  id SERIAL PRIMARY KEY, 
  name VARCHAR(100), 
  email TEXT UNIQUE NOT NULL,
  pet VARCHAR(50),
  age BIGINT,
  entries BIGINT DEFAULT 0, 
  joined TIMESTAMP NOT NULL
);

CREATE TABLE login (
  id serial PRIMARY KEY,
  hash VARCHAR(100) NOT NULL,
  email text UNIQUE NOT NULL 
);

COMMIT;